### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'file'

### ISSUE THREAD

**Issue by alexeyev** [deepmipt/ner#12]
Hi, thanks for the great and a long-awaited tool.

I used to have tensorflow 1.7.0 for CPU installed (initially from provided binaries, then built from source).

In both cases I've bumped into the following issue:
```
$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
>>> tensorflow.__version__
'1.7.0'
>>> import ner
>>> 

  File "/usr/local/lib/python3.5/dist-packages/ner/__init__.py", line 1, in <module>
    from .extractor import Extractor
  File "/usr/local/lib/python3.5/dist-packages/ner/extractor/__init__.py", line 1, in <module>
    from .extractor import Extractor
  File "/usr/local/lib/python3.5/dist-packages/ner/extractor/extractor.py", line 11, in <module>
    from ner.network import NER
  File "/usr/local/lib/python3.5/dist-packages/ner/network.py", line 17, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *  # pylint: disable=redefined-builtin
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/core/framework/node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/core/framework/resource_handle_pb2.py", line 41, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'
```
However, after importing tensorflow first, things do work.

```
$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
>>> tensorflow.__version__
'1.7.0'
>>> import ner
>>> 
```
Prior to noticing the previous hack, I had simply installed the older tensorflow version (I forgot which one, sorry), and that fixed it.

**Comment by alexeyev** [comment]
This doesn't seem to be **ner** package issue. Sorry for the disturbance, best luck!

**Comment by Just-A-Peek** [comment]
I just install tensorflow again.
