### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by SeekPoint** [deepmipt/ner#14]
mldl@mldlUB1604:~/ub16_prj/ner$ python3 ner.py 
Downloading from http://lnsigo.mipt.ru/export/models/ner/ner_model_total_rus.tar.gz to model/ner_model_total_rus.tar.gz
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 44.2M/44.3M [01:07<00:00, 696kB/s]Extracting model/ner_model_total_rus.tar.gz archive into model/
/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py:95: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44.3M/44.3M [01:20<00:00, 696kB/s]
Traceback (most recent call last):
  File "ner.py", line 61, in <module>
    print_predict(query)
  File "ner.py", line 55, in print_predict
    tags = network.predict_for_token_batch([tokens_lemmas])[0]
  File "/home/mldl/ub16_prj/ner/ner/network.py", line 379, in predict_for_token_batch
    batch_x, _ = self.corpus.tokens_batch_to_numpy_batch(tokens_batch)
  File "/home/mldl/ub16_prj/ner/ner/corpus.py", line 205, in tokens_batch_to_numpy_batch
    max_token_len = max([len(token) for utt in batch_x for token in utt])
ValueError: max() arg is an empty sequence
mldl@mldlUB1604:~/ub16_prj/ner$

**Comment by SeekPoint** [comment]
why shut it down
