### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by universome** [deepmipt/ner#9]
Awkward IndexError on specific strings: `Сергее-вичу` gives the error while `Сергее-вич` works fine.

Code to reproduce:
```
import ner

extractor = ner.Extractor(model_url='http://lnsigo.mipt.ru/export/models/ner/ner_model_total_rus.tar.gz')
list(extractor('Сергее-вич')) # works!
list(extractor('Сергее-вичу')) # fails
```

Trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/universome/pyvenvs/zoo/lib/python3.6/site-packages/ner/extractor/extractor.py", line 54, in __call__
    tags = self.network.predict_for_token_batch([tokens_lemmas])[0]
  File "/home/universome/pyvenvs/zoo/lib/python3.6/site-packages/ner/network.py", line 379, in predict_for_token_batch
    batch_x, _ = self.corpus.tokens_batch_to_numpy_batch(tokens_batch)
  File "/home/universome/pyvenvs/zoo/lib/python3.6/site-packages/ner/corpus.py", line 219, in tokens_batch_to_numpy_batch
    x['capitalization'][n, :len(utt)] = [tok[0].isupper() for tok in utt]
  File "/home/universome/pyvenvs/zoo/lib/python3.6/site-packages/ner/corpus.py", line 219, in <listcomp>
    x['capitalization'][n, :len(utt)] = [tok[0].isupper() for tok in utt]
IndexError: string index out of range
```

**Comment by mshnmshn** [comment]
It is caused by pymorphy lemmatizer. The lemmatization of 'вичу' results in an empty string.

**Comment by mshnmshn** [comment]
Fixed
